### ISSUE TITLE
ReQue Output Files vs Pipeline Step * FOR REVIEW *

### ISSUE THREAD

**Issue by kpoots** [hosseinfani/ReQue#13]
This is a brief note on files produced during ReQue testing.  bm25 was used as a ranker. Testing was done with the Wikipedia Retrieval dataset, although I doubt this will make a difference. 

These files were produced, pipeline step by pipeline step, by editing the file ../ReQue/qe/main.py, where the pipeline steps are listed as: 'generate',  'search', 'evaluate', and 'build'. 

The command used was  
python3 -u main.py --anserini ../anserini/ --corpus robust04 --index ../ds/robust04/lucene-index.robust04.pos+docvectors+rawdocs --output ../ds/qe/robust04/ --ranker bm25 --metric map 2>&1 | tee robust04.log

First, the "generate" step was run, then 'search', then 'evaluate', and finally 'build'.  The output directory ../ds/qe/robust04/ was checked after each pipeline step was completed, to see what was created. 

After 'generate', the output directory contains two files per expander, one assuming that expansion terms will be appended to the queries, and the other assuming that the expansion terms will replace the queries. 
After 'search', two files per expander are added to the output directory; these contain are Trec-scored documents for queries and expansion methods.
After 'evaluate', metric files are written to the output directory, for my test, these were map files. 
After 'build', .csv files are written to the output directory. These are summary files which list results. 

It is possible to monitor expansion activity by monitoring files in the output directory. 

It appears to be possible to run only a step or two in the pipline, substitute your own content, and then run the remaining steps in the pipeline. For example, after running "generate", it seems to be possible to substitute your own expanded queries for what is there. Note that this "backdoor" is still under test. 

Please comment with your own experience as you wish !

**Comment by hosseinfani** [comment]
Thanks for the detailed review. Yes, each step produces files for the next step. Indeed, the main step is the generate. 
This is because we build the pipeline incrementally and the way we used the anserini's cli. We are going to use pycerini so that we can use like sdk. 
Should I consider it as a bug, change request, ...?
